### ISSUE TITLE
有办法能监控到应用外部的输入法弹窗吗?

### ISSUE THREAD

**Issue by xiong199208** [pqpo/InputMethodHolder#2]
比如有一个悬浮球的需求,当弹出输入框的时候,将悬浮球顶上去,不要遮挡输入框

**Comment by pqpo** [comment]
在应用内拿到的 InputMethodManager 是一个 Binder Proxy，每个应用都有各自的 Proxy，要想办法 Hook 住所有应用的 Proxy，貌似比较难，而且也没法拿到键盘的高度。可能需要换个思路了。
