### ISSUE TITLE
【提个建议】希望后续能在接口里面可以返回多一个键盘高度的参数

### ISSUE THREAD

**Issue by 164738777** [pqpo/InputMethodHolder#3]
谢谢大佬，这个挺好用的，上次搞键盘监听好麻烦的。

**Comment by pqpo** [comment]
这个方法 Hook 的是 InputMethodManager 的 showSoftInput 方法：
public boolean showSoftInput(View view, int flags) {
        return showSoftInput(view, flags, null);
 }
这里的 View 是 The currently focused view, which would like to receive soft keyboard input.
应该拿不到键盘高度。
