### ISSUE TITLE
关于Hook住EditText中InputConnection的问题

### ISSUE THREAD

**Issue by 985557461** [pqpo/InputMethodHolder#4]
虚拟键盘在更新输入框文字的时候是通过InputConnection这个最后来实现的，为什么Hook不住EditText中的InputConnection呢？
实际效果是Hook完毕后，点击虚拟键盘上面的文字，并没有回调InputConnection中相应的方法

**Comment by pqpo** [comment]
能贴一下 hook 的代码吗
