### ISSUE TITLE
监听键盘收起

### ISSUE THREAD

**Issue by 985557461** [pqpo/InputMethodHolder#5]
我发现输入法启动的时候，会回调IInputMethodManagerService中的windowGainedFocus该方法，这个方法中会创建EditText和InputMethodService的通道，即IInputConnectionWrapper，在创建这个Binder的过程中，需要参数InputConnection对象，而这里是可以hook住的。这样键盘收起的时候就可以监听到了。测试6.0可以检测到，不知道对于完善你的Hook是否有帮助，麻烦了。

**Comment by pqpo** [comment]
感谢！回头我研究研究。你也可以提交 PR 呀：）

**Comment by paozhuanyinyu** [comment]
IInputConnectionWrapper是否hook成功
