### ISSUE TITLE
mi4 6.0上只能监听到显示，并且同一次显示会回调两次三次不等，隐藏没有回调

### ISSUE THREAD

**Issue by 0LongLongAgo** [pqpo/InputMethodHolder#6]

**Comment by pqpo** [comment]
是点击按钮隐藏的不行监听到？

**Comment by 0LongLongAgo** [comment]
在输入法右上角有个向下的箭头，点击隐藏输入法的时候，没有监听到，后来我换了个https://github.com/yshrsmz/KeyboardVisibilityEvent，可以一起学习下

**Comment by pqpo** [comment]
我这种方案隐藏的话，只能监听到点击界面上的那个按钮关闭键盘。 你说的那个方案是通过判断布局改变实现的，也是一个很好的思路，但是对 softInputMode 有限制。
