### ISSUE TITLE
点击返回键后，输入法框关闭，这个监听不到呀

### ISSUE THREAD

**Issue by nianzixin** [pqpo/InputMethodHolder#8]

**Comment by BlackC0** [comment]
+1，现在全屏状态下 输入法弹出后单击的返回键（严格来说可能不是返回键 onKeyDown没有监听到事件）
输入法下去后 没有监听

**Comment by pqpo** [comment]
Readme 中已经说明了：https://github.com/pqpo/InputMethodHolder#defect
